// Auto-generated by RecoverPath edge trainer
#ifndef COUGH_MODEL_DATA_H
#define COUGH_MODEL_DATA_H
#ifdef __cplusplus
extern "C" {
#endif
extern const unsigned char g_cough_model_data[];
extern const unsigned int g_cough_model_data_len;
#ifdef __cplusplus
}
#endif
#endif // COUGH_MODEL_DATA_H